import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { parse } from "parse5";
import { IDBFactory } from "fake-indexeddb";
import R from "../src/run.js";
import { createProfileStore } from "../src/profile-store.js";
import {
  verifyRaidBlueprint,
  prepareRaidRewards,
  registerRaidBlueprint,
  getRaidAppearance,
} from "../src/raid/index.js";
import {
  analyzeStaticCode,
  reconstructStaticCode,
} from "../server/site-ingest/code.js";
import {
  createSafeStyleReader,
  CSS_LIMITS,
} from "../server/site-ingest/css.js";
import { createStaticIngestService } from "../server/site-ingest/service.js";
import { DEFAULT_PUBLIC_SOURCES } from "../server/site-ingest/config.js";

const PAGE = "https://books.toscrape.com/";
const SHEET = PAGE + "static/oscar/css/styles.css";
const OLD_CAPTURE =
  "capture_094a736bbe69ed43d3f86fce66ca79264af13f519a5ca6193fd5b3ae8c595d2d";
const NEW_CAPTURE =
  "capture_b51a0697f50e53fd012abd53d1225079e61099a4f71884658397e90dd5624fd5";
const OLD_APPEARANCE =
  "appearance_b1b9ded9742f514c6dde3c717820d091d220ffdd18e0e8a1e260d6011eb88446";
const hash = (value) => createHash("sha256").update(value).digest("hex");
const fixture = (path) =>
  readFile(new URL(`../fixtures/raid/${path}`, import.meta.url), "utf8");
const oldCapture = async () =>
  JSON.parse(await fixture("compatibility/books-before-child-selectors.json"));
async function recordedSource() {
  const [html, css] = await Promise.all([
    fixture("public-source/books.html"),
    fixture("public-source/books.css"),
  ]);
  return {
    requestedUrl: PAGE,
    html,
    sourceHash: hash(html),
    bytes: Buffer.byteLength(html),
    capturedAt: "2026-10-03T03:20:00.000Z",
    extraction: { title: "Books", candidates: [] },
    stylesheets: [{ css, sourceHash: hash(css), url: SHEET }],
  };
}
function nodesById(html) {
  const found = new Map();
  const visit = (node) => {
    const id = node.attrs?.find((attribute) => attribute.name === "id")?.value;
    if (id) found.set(id, node);
    for (const child of node.childNodes ?? []) visit(child);
  };
  visit(parse(html));
  return found;
}

// This fixture was independently matched to unmodified pre-repair production
// output at this exact timestamp. Pin its full historical payload, not a fixture
// regenerated by the new parser. These checks make no browser-pixel claim.
test("QA: pre-child-selector capture keeps its exact sealed historical payload", async () => {
  const legacy = await oldCapture();
  assert.equal(
    hash(JSON.stringify(legacy)),
    "df768a21e42f6bfda965c4237e3074e18e6830a363707d7c755bd2b8ec2151e8",
  );
  assert.equal(legacy.captureId, OLD_CAPTURE);
  assert.equal(legacy.components[1].appearanceId, OLD_APPEARANCE);
  assert.deepEqual(legacy.components[1].appearance.primitives[1].rect, {
    x: 12,
    y: 8,
    w: 168,
    h: 24,
  });
  assert.equal((await verifyRaidBlueprint(legacy)).ok, true);
});

test("QA: recorded-source child padding changes only the Books anchor and capture metadata", async () => {
  const source = await recordedSource();
  assert.equal(
    source.sourceHash,
    "9fdd63da34161ebd13408d7a85105f83ec3c9f351c5d77cd0aa578790e121c1e",
  );
  assert.equal(
    source.stylesheets[0].sourceHash,
    "d497d4a0d52686ccd30f5941b02867075870372cdfe37adbcb0be74fdeed94cf",
  );
  const legacy = await oldCapture();
  const fresh = await reconstructStaticCode(source);
  assert.equal(fresh.captureId, NEW_CAPTURE);
  assert.equal(fresh.components.length, 8);
  assert.equal(fresh.components[1].appearance.primitives[1].text, "Books");
  assert.deepEqual(fresh.components[1].appearance.primitives[1].rect, {
    x: 15,
    y: 10,
    w: 162,
    h: 20,
  });
  assert.notEqual(fresh.components[1].appearanceId, OLD_APPEARANCE);
  const expected = structuredClone(legacy);
  expected.captureId = fresh.captureId;
  expected.analysis.css.rules = 576;
  expected.components[1].appearanceId = fresh.components[1].appearanceId;
  expected.components[1].appearance.primitives[1].rect = {
    x: 15,
    y: 10,
    w: 162,
    h: 20,
  };
  assert.deepEqual(
    fresh,
    expected,
    "all other component, source, layout and warning data must remain unchanged",
  );
  assert.equal((await verifyRaidBlueprint(fresh)).ok, true);
  assert.ok(fresh.components.every((part) => part.sourceRect === null));
});

test("QA: old trophies and pending rewards coexist byte-for-byte with the new capture", async () => {
  const legacy = await oldCapture();
  const fresh = await reconstructStaticCode(await recordedSource());
  assert.notEqual(fresh.captureId, legacy.captureId);
  const factory = new IDBFactory();
  const store = createProfileStore(factory);
  await store.recordRaidVictory(legacy, "qa-child-old-claimed");
  const oldReward = prepareRaidRewards(legacy, "qa-child-old-claimed")[1];
  await store.claimRaidReward(R.newRun("lab"), oldReward, legacy);
  await store.recordRaidVictory(legacy, "qa-child-old-pending");
  const captureBytes = JSON.stringify(
    await store.getBlueprint(legacy.captureId),
  );
  const trophyBytes = JSON.stringify((await store.listTrophies())[0]);
  await store.recordRaidVictory(fresh, "qa-child-new-claimed");
  const newReward = prepareRaidRewards(fresh, "qa-child-new-claimed")[1];
  await store.claimRaidReward(R.newRun("lab"), newReward, fresh);
  const reopened = createProfileStore(factory);
  assert.equal(
    JSON.stringify(await reopened.getBlueprint(legacy.captureId)),
    captureBytes,
  );
  assert.equal(
    JSON.stringify(
      (await reopened.listTrophies()).find(
        (t) => t.battleId === oldReward.battleId,
      ),
    ),
    trophyBytes,
  );
  assert.deepEqual(await reopened.getBlueprint(fresh.captureId), fresh);
  const pending = await reopened.listPendingRaids();
  assert.equal(pending.length, 1);
  assert.equal(JSON.stringify(pending[0].blueprint), captureBytes);
  const pendingReward = prepareRaidRewards(
    pending[0].blueprint,
    pending[0].battleId,
  )[1];
  assert.equal(pendingReward.appearanceId, OLD_APPEARANCE);
  assert.notEqual(pendingReward.appearanceId, newReward.appearanceId);
  const claim = await reopened.claimRaidReward(
    R.newRun("lab"),
    pendingReward,
    pending[0].blueprint,
  );
  assert.equal(claim.trophy.item.appearanceId, OLD_APPEARANCE);
  assert.equal(claim.trophy.item.provenanceId, OLD_CAPTURE);
  assert.deepEqual(await reopened.listPendingRaids(), []);
  assert.equal(
    JSON.stringify(await reopened.getBlueprint(legacy.captureId)),
    captureBytes,
  );
  await registerRaidBlueprint(legacy);
  await registerRaidBlueprint(fresh);
  assert.deepEqual(
    getRaidAppearance(OLD_APPEARANCE),
    legacy.components[1].appearance,
  );
  assert.deepEqual(
    getRaidAppearance(newReward.appearanceId),
    fresh.components[1].appearance,
  );
});

test("QA: direct children and mixed ancestor paths never flatten into descendants", () => {
  const nodes = nodesById(
    '<div class="a"><section class="b"><div class="b"><a id="nested">Nested</a></div><a id="direct">Direct</a><div><a id="wrapped">Wrapped</a></div></section></div><section class="b"><a id="outside">Outside</a></section>',
  );
  for (const [selector, expected] of [
    [".a>.b>a", ["direct"]],
    [".a > .b a", ["nested", "direct", "wrapped"]],
    [".a .b>a", ["nested", "direct"]],
    [".a>.b>.b>a", ["nested"]],
    [".a .b a", ["nested", "direct", "wrapped"]],
  ]) {
    const reader = createSafeStyleReader([`${selector}{padding:7px}`]);
    const actual = [...nodes]
      .filter(([, node]) => reader.styleFor(node).padding?.[0] === 7)
      .map(([id]) => id);
    assert.deepEqual(actual, expected, selector);
  }
});

test("QA: child support retains exact selector limits and rejects other grammar", () => {
  assert.deepEqual(CSS_LIMITS, {
    bytes: 262144,
    rules: 1024,
    blocks: 4096,
    declarations: 64,
    selectorParts: 4,
  });
  for (const selector of [
    "> a",
    "a >",
    "a >> b",
    "a > > b",
    "a + b",
    "a ~ b",
    "a || b",
    "a[b]",
    "a:hover",
    ":root > a",
    "* > a",
    "a>b>c>d>e",
    "a b c d e",
    "a#one#two>b",
  ]) {
    const reader = createSafeStyleReader([`${selector}{padding:7px}`]);
    assert.equal(reader.rules, 0, selector);
  }
  for (const selector of ["a>b>c>d", "a > b c>d", "a\t>\nb\fc > d"]) {
    assert.equal(
      createSafeStyleReader([`${selector}{padding:7px}`]).rules,
      1,
      selector,
    );
  }
  const html =
    '<div class="a">' +
    '<div class="b">'.repeat(57) +
    '<a id="deep">Deep</a>' +
    "</div>".repeat(58);
  const reader = createSafeStyleReader([
    ".a>.b .b>a{padding:7px}.absent>.b .b>a{padding:9px}",
  ]);
  assert.deepEqual(
    reader.styleFor(nodesById(html).get("deep")).padding,
    [7, 7, 7, 7],
  );
  assert.throws(
    () =>
      analyzeStaticCode(
        "<div>".repeat(70) + "<h1>Too deep</h1>" + "</div>".repeat(70),
      ),
    /source-too-large/,
  );
});

test("QA: child hiding stays conservative while nested nonchildren stay visible", () => {
  const result = analyzeStaticCode(
    '<style>.hide>.secret{display:none}.secret{display:block}.hide>button{color:#123456;background:url(https://unreviewed.example/image)}</style><div class="hide"><section class="secret"><h1>SECRET</h1></section><div><section class="secret"><h2>Visible nested</h2></section></div><button>Add to basket</button></div>',
  );
  assert.doesNotMatch(JSON.stringify(result), /SECRET|unreviewed|url\(/);
  assert.ok(
    result.candidates.some((candidate) => candidate.label === "Visible nested"),
  );
  const purchase = result.candidates.find(
    (candidate) => candidate.kind === "purchase",
  );
  assert.equal(purchase.style.color, "#123456");
  assert.equal(purchase.style.background, undefined);
});

test("QA: a child-selector capture requests only the two unchanged reviewed Books resources", async () => {
  assert.deepEqual(DEFAULT_PUBLIC_SOURCES, [
    {
      origin: "https://books.toscrape.com",
      pageUrl: PAGE,
      stylesheetUrl: SHEET,
    },
    { origin: "https://example.com", pageUrl: "https://example.com/" },
  ]);
  const source = await recordedSource();
  const requests = [];
  const service = createStaticIngestService({
    transport: async (url, options) => {
      requests.push(url);
      assert.equal(options.credentials, "omit");
      assert.equal(options.redirect, "error");
      return new Response(
        url === SHEET ? source.stylesheets[0].css : source.html,
        {
          headers: { "content-type": url === SHEET ? "text/css" : "text/html" },
        },
      );
    },
  });
  const result = await service.reconstruct(PAGE);
  assert.equal(result.ok, true, result.error);
  assert.deepEqual(requests, [PAGE, SHEET]);
  assert.deepEqual(result.value.components[1].appearance.primitives[1].rect, {
    x: 15,
    y: 10,
    w: 162,
    h: 20,
  });
  assert.equal(result.value.analysis.sourceHash, source.sourceHash);
  assert.deepEqual(result.value.analysis.css.stylesheetHashes, [
    source.stylesheets[0].sourceHash,
  ]);
  assert.doesNotMatch(
    JSON.stringify(result.value),
    /\.nav\s*>|stylesheetUrl|static\/oscar/,
  );
});
