import type { Faction, PartDefinition } from "./types.js";
import { FUSED_PARTS } from "./fusion.js";
import { BALANCE_PARTS } from "./catalog/balance-parts.js";
import { SOCIAL_PARTS } from "./catalog/social-parts.js";
import { KNOWLEDGE_PARTS } from "./catalog/knowledge-parts.js";
import { COMMUNITY_PARTS } from "./catalog/community-parts.js";
import { AUDIO_PARTS } from "./catalog/audio-parts.js";

// Shared canonical registry; importing this module does not load site templates.
const WIDTH = 960;
const HEIGHT = 680;
const LOAD_LIMIT = 56;

const PARTS: Record<string, PartDefinition> = {};
type PartRow = [
  string,
  string,
  string,
  string,
  string,
  number,
  number,
  number,
  number,
  number,
  number,
  string,
  Partial<PartDefinition>?,
];
function define(faction: Faction, rows: PartRow[]) {
  for (const r of rows) {
    const [
      id,
      name,
      kind,
      tags,
      layout,
      w,
      h,
      cd,
      value,
      load,
      price,
      desc,
      extra = {},
    ] = r;
    PARTS[id] = {
      id,
      name,
      faction,
      kind,
      tags: tags.split(" "),
      layout,
      w,
      h,
      cd,
      value,
      load,
      price,
      desc,
      added: !!extra.added,
      minW: Math.min(
        w,
        layout === "button" ? 72 : layout === "link" ? 80 : 140,
      ),
      minH: Math.min(h, 28),
      maxW: 920,
      maxH: 500,
      ...extra,
    };
  }
}
define("youtube", [
  [
    "yt_play",
    "動画プレイヤー",
    "attack",
    "video media",
    "media",
    560,
    280,
    2.5,
    8,
    5,
    7,
    "2.5秒ごとに8ダメージ。再生が広告とメンバー登録を起動する。下にシークバーや操作ボタンをつなげられる。",
    { minW: 240, minH: 144 },
  ],
  [
    "yt_speed",
    "2× 再生速度",
    "passive",
    "control media-control",
    "button",
    104,
    40,
    0,
    0,
    3,
    8,
    "同じ認識済み動画プレイヤー構造の動画本体を2倍速にする。文字・購入・再発動UIは加速しない。上限2倍。",
    { minW: 72, minH: 32 },
  ],
  [
    "yt_ad",
    "動画広告",
    "reactive",
    "economy ad",
    "banner",
    280,
    80,
    0,
    1,
    2,
    5,
    "つながる動画が通常再生されるたび$1。再発動では収益を生まない。広告収益を近くの変換先1つへ流せる。",
    { minW: 160, minH: 48 },
  ],
  [
    "yt_sub",
    "メンバー登録",
    "reactive",
    "economy subscription",
    "button",
    184,
    40,
    0,
    2,
    2,
    6,
    "近くの動画が通常再生を3回行うたび$2。再発動は数えない。ボタングループの一員にもなる。",
    { minW: 144, minH: 32 },
  ],
  [
    "yt_like",
    "高評価ボタン",
    "attack",
    "button media-control",
    "button",
    112,
    40,
    2.8,
    4,
    2,
    4,
    "2.8秒ごとに4ダメージ。発動のたびに威力+1、最大+5。動画と一体化しても働く。",
    { added: true, minW: 72, minH: 32 },
  ],
  [
    "yt_progress",
    "シークバー",
    "passive",
    "control media-control",
    "progress",
    560,
    22,
    0,
    0,
    1,
    4,
    "動画の直下に連結すると再生威力+25%。再生進捗が実際にバーを動かす。",
    { added: true, minW: 160, minH: 16 },
  ],
  [
    "yt_caption",
    "字幕 CC",
    "passive",
    "text control media-control",
    "button",
    88,
    40,
    0,
    0,
    1,
    4,
    "同じプレイヤー内・近接の動画にシールド貫通率+25%。字幕が戦闘中に更新される。",
    { added: true, minW: 64, minH: 32 },
  ],
  [
    "yt_autoplay",
    "自動再生",
    "echo",
    "control media-control",
    "toggle",
    176,
    40,
    6,
    0.45,
    2,
    6,
    "6秒ごとに、つながる動画の最後の通常攻撃を45%威力で再生。原本の発動前は待機。再発動は収益や成長を連鎖させない。",
    { added: true, minW: 128, minH: 32 },
  ],
  [
    "yt_notify",
    "通知ベル",
    "shield",
    "control media-control",
    "button",
    72,
    40,
    4,
    5,
    1,
    4,
    "4秒ごとにシールド5。動画と一体化すると+2。ベルと通知バッジが反応する。",
    { added: true, minW: 48, minH: 32 },
  ],
]);
define("amazon", [
  [
    "am_buy",
    "カートに入れる",
    "attack",
    "commerce button",
    "button",
    168,
    40,
    3,
    9,
    2,
    5,
    "3秒ごとに9ダメージ。戦闘収益$5ごとに威力+1、最大+8。検索欄にもつなげられる。",
    { minW: 128, minH: 32 },
  ],
  [
    "am_cart",
    "ショッピングカート",
    "reactive",
    "commerce cart",
    "cart",
    280,
    100,
    0,
    15,
    3,
    7,
    "選択された近接収益のチャージを$3消費して15ダメージ。他の変換先と同じ収益を複製しない。累計収益やラン資金は減らない。",
    { minW: 200, minH: 76 },
  ],
  [
    "am_prime",
    "Prime配送",
    "passive",
    "commerce control",
    "button",
    144,
    40,
    0,
    0,
    2,
    5,
    "近接するcommerce UIを1.5倍速にする。検索フォームやボタン列に連結できる。",
    { minW: 112, minH: 32 },
  ],
  [
    "am_deal",
    "タイムセール",
    "income",
    "commerce economy",
    "banner",
    280,
    52,
    5,
    2,
    2,
    6,
    "購入UI・商品情報のそばなら5秒ごとに$2。セール残り時間が進む。",
    { minW: 176, minH: 44 },
  ],
  [
    "am_product",
    "商品情報",
    "attack",
    "commerce product",
    "product",
    280,
    196,
    4,
    11,
    4,
    7,
    "4秒ごとに11ダメージ。直下の購入操作と連結すると、購入ボタンを20%強化。",
    { added: true, minW: 200, minH: 150 },
  ],
  [
    "am_quantity",
    "数量セレクト",
    "passive",
    "commerce control",
    "field",
    112,
    40,
    0,
    0,
    1,
    4,
    "近くの購入・商品UIの威力+20%。他サイトのボタンとつながる入力欄。",
    { added: true, minW: 80, minH: 32 },
  ],
  [
    "am_rating",
    "星評価・レビュー",
    "passive",
    "commerce text",
    "rating",
    280,
    32,
    0,
    0,
    1,
    4,
    "近くのcommerce攻撃の威力+20%。文字部品としても扱う。",
    { added: true, minW: 160, minH: 24 },
  ],
  [
    "am_coupon",
    "クーポンチェック",
    "income",
    "commerce economy",
    "check",
    280,
    36,
    6,
    2,
    1,
    4,
    "購入UI・商品情報が近くにあれば6秒ごとに$2。クーポンが適用される。",
    { added: true, minW: 192, minH: 30 },
  ],
  [
    "am_wish",
    "ほしい物リスト",
    "heal",
    "commerce button",
    "button",
    192,
    40,
    5,
    5,
    2,
    5,
    "5秒ごとにHP5回復。ボタングループにすると回復の待ち時間も短くなる。",
    { added: true, minW: 136, minH: 32 },
  ],
]);
define("google", [
  [
    "go_search",
    "検索窓",
    "attack",
    "text search",
    "search",
    420,
    44,
    3.6,
    8,
    3,
    6,
    "3.6秒ごとに8ダメージ。近くの別サイト系統ごとに威力+2（4系統・最大+8）。ボタンと連結すると検索フォームになり威力+30%。",
    { minW: 192, minH: 36 },
  ],
  [
    "go_lucky",
    "I'm Feeling Lucky",
    "attack",
    "text button",
    "button",
    184,
    40,
    2.8,
    6,
    2,
    5,
    "2.8秒ごとに6ダメージ。3発目は3倍。検索欄とつなげると同じフォームとして動く。",
    { minW: 160, minH: 32 },
  ],
  [
    "go_suggest",
    "検索サジェスト",
    "passive",
    "text search",
    "suggest",
    420,
    84,
    0,
    0,
    2,
    6,
    "近接するtext攻撃の威力+40%。検索フォームの直下に置くと一続きの候補パネルになる。",
    { minW: 192, minH: 56 },
  ],
  [
    "go_ads",
    "スポンサー検索結果",
    "reactive",
    "economy ad text",
    "result",
    400,
    84,
    0,
    1,
    2,
    5,
    "近くの文字UIが通常の時間発動を行うたび$1。再発動と再発動コントローラからは収益を生まない。検索結果として並べられる。",
    { minW: 240, minH: 72 },
  ],
  [
    "go_tabs",
    "検索カテゴリタブ",
    "passive",
    "search navigation text",
    "tabs",
    440,
    40,
    0,
    0,
    1,
    4,
    "近くの検索・検索結果を20%加速。アクティブなタブに下線が移動する。",
    { added: true, minW: 264, minH: 32 },
  ],
  [
    "go_voice",
    "音声検索",
    "attack",
    "search button",
    "button",
    72,
    44,
    3.4,
    5,
    1,
    4,
    "3.4秒ごとに5ダメージ。検索フォーム内なら威力+30%。マイクが波形になる。",
    { added: true, minW: 48, minH: 36 },
  ],
  [
    "go_result",
    "検索結果リンク",
    "attack",
    "search text link",
    "result",
    560,
    96,
    3.2,
    8,
    3,
    6,
    "3.2秒ごとに8ダメージ。タイトル・URL・説明の3層を持つ検索結果。文字系の連携が効く。",
    { added: true, minW: 260, minH: 80 },
  ],
  [
    "go_translate",
    "翻訳セレクト",
    "passive",
    "text search control",
    "field",
    184,
    40,
    0,
    0,
    2,
    5,
    "近くの、別サイト由来のtext攻撃を25%強化。入力欄・ボタンと連結可能。",
    { added: true, minW: 136, minH: 32 },
  ],
  [
    "go_page",
    "検索ページ送り",
    "echo",
    "search navigation text",
    "pagination",
    320,
    36,
    6,
    0.5,
    2,
    6,
    "6秒ごとに近くの文字攻撃の最後の通常発動を50%で再現。原本の発動前は待機。通常発動回数や収益は増やさない。",
    { added: true, minW: 192, minH: 30 },
  ],
]);
define("retro", [
  [
    "ab_link",
    "青いハイパーリンク",
    "attack",
    "text link navigation",
    "link",
    192,
    32,
    1.8,
    4,
    1,
    3,
    "1.8秒ごとに4ダメージ。余白率による最大+3は、ページ全体の見た目順で先頭2本だけ。攻撃ナビが6個を超えると、超過1個につき全攻撃ナビの発動間隔+5%。縦横につなぐ速さと導線は維持。",
    { minW: 96, minH: 24 },
  ],
  [
    "ab_table",
    "tableの二重枠",
    "shield",
    "container text",
    "container",
    280,
    176,
    3,
    4,
    2,
    4,
    "3秒ごとにシールド4。内側に文字UIを入れると+3。枠は他のUIを本当に内包できる。",
    { minW: 200, minH: 120, container: true, padding: [38, 12, 12, 12] },
  ],
  [
    "ab_counter",
    "訪問カウンター",
    "reactive",
    "economy text",
    "counter",
    288,
    26,
    0,
    1,
    1,
    4,
    "近くの通常の時間発動を4回数えるたび$1。再発動と再発動コントローラは数えない。フッターにも置ける細長いカウンター。",
    { minW: 224, minH: 24 },
  ],
  [
    "ab_marquee",
    "流れるmarquee",
    "echo",
    "text legacy",
    "marquee",
    560,
    28,
    5.5,
    0.55,
    2,
    7,
    "5.5秒ごとに右側または直下の攻撃UIの最後の通常発動を55%で再現。原本の発動前は待機。流れる文字が進行方向を示す。",
    { minW: 200, minH: 24 },
  ],
  [
    "ab_heading",
    "大きな明朝見出し",
    "attack",
    "text heading",
    "heading",
    576,
    56,
    4.5,
    10,
    3,
    5,
    "4.5秒ごとに10ダメージ。独立したカードではなく、ページの見出しそのもの。文字を編集できる。",
    { added: true, minW: 224, minH: 42 },
  ],
  [
    "ab_hr",
    "水平線 <hr>",
    "shield",
    "text separator",
    "rule",
    560,
    16,
    5,
    5,
    1,
    3,
    "5秒ごとにシールド5。近くに文字UIがあると+2。ページを実際に区切る細い罫線。",
    { added: true, minW: 160, minH: 8, maxH: 32 },
  ],
  [
    "ab_mail",
    "メールリンク",
    "income",
    "economy text link navigation",
    "link",
    224,
    32,
    6,
    2,
    1,
    4,
    "6秒ごとに$2。ナビとして連結すると発動が早くなる。実際のメールは送信しない。",
    { added: true, minW: 144, minH: 24 },
  ],
  [
    "ab_nav",
    "旧式ナビリンク",
    "attack",
    "text link navigation",
    "link",
    176,
    32,
    2.4,
    5,
    1,
    3,
    "2.4秒ごとに5ダメージ。青リンクを並べると、実際のナビゲーションとして連結する。",
    { added: true, minW: 112, minH: 24 },
  ],
  [
    "ab_guestbook",
    "掲示板・BBS",
    "heal",
    "text legacy",
    "guestbook",
    320,
    132,
    5.2,
    6,
    3,
    5,
    "5.2秒ごとにHP6回復。戦闘中に書き込みが更新される、昔の掲示板。",
    { added: true, minW: 240, minH: 96 },
  ],
]);
define("gov", [
  [
    "gov_pdf",
    "PDFダウンロード行",
    "attack",
    "text document",
    "document",
    280,
    48,
    5.5,
    18,
    3,
    7,
    "5.5秒ごとに18ダメージ。半分はシールドを無視する。PDFアイコン付きのダウンロード行。",
    { minW: 184, minH: 40 },
  ],
  [
    "gov_form",
    "電子申請フォーム",
    "shield",
    "document form container",
    "container",
    280,
    200,
    4,
    7,
    3,
    5,
    "4秒ごとにシールド7。チェック・送信UIを内側に置ける。フォーム内の部品は20%加速。",
    { container: true, padding: [56, 16, 16, 16], minW: 224, minH: 144 },
  ],
  [
    "gov_font",
    "文字サイズ変更",
    "passive",
    "control typography",
    "font",
    232,
    36,
    0,
    0,
    1,
    5,
    "近接するtext攻撃の威力+50%。ページ内の読みやすさ用UIが戦闘では文字強化になる。",
    { minW: 208, minH: 32 },
  ],
  [
    "gov_notice",
    "重要なお知らせ",
    "heal",
    "text document",
    "notice",
    560,
    56,
    5,
    5,
    2,
    5,
    "5秒ごとにHP5回復。近くに別の書類UIがあると+2。サイト内のお知らせ帯として表示。",
    { minW: 240, minH: 48 },
  ],
  [
    "gov_breadcrumb",
    "パンくずリスト",
    "passive",
    "document navigation text",
    "breadcrumb",
    560,
    28,
    0,
    0,
    1,
    3,
    "近くのdocument UIを15%加速。ページ上部の導線として働く。",
    { added: true, minW: 264, minH: 24 },
  ],
  [
    "gov_check",
    "同意チェックボックス",
    "shield",
    "document form",
    "check",
    232,
    32,
    5,
    4,
    1,
    4,
    "5秒ごとにシールド4。申請フォーム内では20%加速。実際のチェックとして操作できる。",
    { added: true, minW: 184, minH: 28 },
  ],
  [
    "gov_accordion",
    "折りたたみ案内",
    "heal",
    "document container text",
    "container",
    328,
    160,
    5,
    5,
    2,
    5,
    "5秒ごとにHP5回復。ほかの部品を入れられる案内枠。プレビューで折りたためる。",
    {
      added: true,
      container: true,
      padding: [44, 12, 12, 12],
      minW: 240,
      minH: 112,
    },
  ],
  [
    "gov_page",
    "ページ番号ボタン",
    "echo",
    "document navigation",
    "pagination",
    280,
    36,
    6,
    0.45,
    2,
    5,
    "6秒ごとに近くの書類攻撃の最後の通常発動を45%で再現。原本の発動前は待機。通常発動回数や収益は増やさない。",
    { added: true, minW: 216, minH: 32 },
  ],
  [
    "gov_submit",
    "申請を送信",
    "attack",
    "document form button text",
    "button",
    184,
    40,
    4.5,
    10,
    2,
    5,
    "4.5秒ごとに10ダメージ。申請フォーム内にあると発動ごとに$1の処理報酬。",
    { added: true, minW: 136, minH: 32 },
  ],
]);
// Fusion-only UIs (src/fusion.ts) join the catalogue before it is frozen.
Object.assign(PARTS, BALANCE_PARTS, SOCIAL_PARTS, KNOWLEDGE_PARTS, COMMUNITY_PARTS, AUDIO_PARTS, FUSED_PARTS);
for (const p of Object.values(PARTS)) {
  Object.freeze(p.tags);
  if (p.replayTags) Object.freeze(p.replayTags);
  Object.freeze(p);
}
Object.freeze(PARTS);

export { PARTS, WIDTH, HEIGHT, LOAD_LIMIT };
